### ISSUE TITLE
Disable docstring default argument parsing by default to reduce subtle bugs.

### ISSUE THREAD

**Issue by basveeling** [omni-us/jsonargparse#258] opened 2023-03-24 16:49 UTC
## 🐛 Bug report
Lightning torchmetrics.`Metric`s silently fail to sync across gpus when initialized with jsonargparse (as used in the LightningCLI)

This happens due the following combination of factors.
- jsonargparse has a docstring parsing function enabled when installed with `pip install jsonargparse[signatures]`
- `torchmetrics.Metric` has a docstring that mentions an optional` distributed_available_fn`
- If `distributed_available_fn` is not set in `**kwargs`, `Metric.__init__` sets a default pytorch function which enables ddp syncing of metrics
- When a metric is initialized in a yaml config, jsonargparse recognizes the `distributed_available_fn` field in the docstring of `Metric.__init__` and passes a default value of `distributed_available_fn=None` when initializing the metric object.
- Hence, any subclass of `Metric` initialized by jsonargparse has `distributed_available_fn = None`. These metrics silently fail to sync across gpus due to this line: https://github.com/Lightning-AI/metrics/blob/v0.11.4/src/torchmetrics/metric.py#L114

### To reproduce

Initialize a Metric object using jsonargparse, find `metric.distributed_available_fn == None`

### Expected behavior

Do not pass a value for optional **kwargs discovered by the docstring parser if no default value is provided in the docstring, as this causes unexpected behaviour that is difficult to debug.

Alternatively, disable docstring parsing by default?

### Environment

- jsonargparse version: 4.20.0
- Python version : 3.10
- How jsonargparse was installed:`pip install jsonargparse[signatures]`
- OS (e.g., Linux): Linux

**Comment by mauvilsa** [comment] 2023-03-26 16:40
Thank you for reporting!

Why is it that you think that the issue is related to docstrings? If `docstring-parser` is uninstalled, does it not fail?

`jsonargparse` looks at the source code to determine which parameters are accepted. The fact that in the code there is `kwargs.pop("distributed_available_fn", jit_distributed_available)` means that it will be discovered (unrelated to docstrings), and the default will be `None`.

I haven't looked too much in detail. However, to me it seems that there is no bug. It is expected that `distributed_available_fn` is  passed with value `None`. I would argue that the problem is in the `Metric` class. It should be implemented in a way that it doesn't fail if given `distributed_available_fn=None`.

**Comment by mauvilsa** [comment] 2023-08-29 21:21
Closing this since it seems to have been fixed in https://github.com/Lightning-AI/torchmetrics/commit/4d5147a083a8972916fbf7f457347fdf10dac7ea.

**Closed by mauvilsa** 2023-08-29 21:21 UTC
Labels: bug
