### ISSUE TITLE
[Feature Request] Support for `**` described parameters not part of the parent class

### ISSUE THREAD

**Issue by quancs** [omni-us/jsonargparse#114] opened 2022-01-14 08:39 UTC
moved from https://github.com/PyTorchLightning/pytorch-lightning/discussions/8561#discussioncomment-1962027

A handle for `**` described parameters is necessary in  jsonargparse, as we could never force the users to not have that kind of parameters in python. [**DDPPlugin**](https://github.com/PyTorchLightning/pytorch-lightning/discussions/8561) and [**PyTorchProfiler**](https://github.com/PyTorchLightning/pytorch-lightning/issues/10859#issuecomment-1001949302) are two examples for the feature requested.

My idea about this is we could regard the parameters with `**` prefix as a dict that doesn't need type checking. For example, in the following code, the `**` describes `any_name`, so `any_name` is a dict that does not need type checking. 

```python
class A:
  def __init__(self,**any_name):
      print(type(any_name))
      print(any_name)

A(a='123',b=2)
```

And as we could see from its output below, the `any_name` is indeed a dict.
```
<class 'dict'>
{'a': '123', 'b': 2}
```

To construct such sepcial `any_name`, we could specify its keys and values like the config followed without intervening the type checking of other paramters:
```
class_path: module.A
init_args:
  any_name:
    a: '123'
    b: 2
  #other_parameters_that_need_type_checking
```

**Comment by quancs** [comment] 2022-01-14 08:42
Thoughts about this idea from @mauvilsa is:

> using `any_name` has the downside that it forces people to know what is the particular name that was used internally in the code. But true that it guarantees that there is no clash with the names of other parameters. Making it a fixed name does risk a clash (though highly unlikely for `__*__`), but has advantages. If people see it being used, they can easily find in the documentation what it does. The actual name to use I am not yet sure. `__kwargs__` is one option, but better if it is more scope specific. This would only be for parameters that can't be resolved via class inheritance, so another option could be `__unresolved__`.

**Comment by quancs** [comment] 2022-01-14 08:57
I'm OK with `any_name`, `__kwargs__`, and `__unresolved__`. But I think `any_name` is a better way, not only for name clash, but also for consistency with other paramters. Besides, in the function side and user side, `any_name` is just one parameter like other parameters, so config it in the config file is a very natural thinking.

**Comment by mauvilsa** [comment] 2022-01-17 08:36
I think a clarification is needed because how the feature request is described currently does not align well with the design of jsonargparse. The `*args` and `**kwargs` of the `__init__` methods of classes is already supported in a very specific way. They are used to identify more named parameters and their types from parent classes (also see https://github.com/PyTorchLightning/pytorch-lightning/discussions/8561#discussioncomment-1060713). This is by design and will continue to be the main way these parameters are supported. This design decision does mean things will or not work depending on how the `**kwargs` is used in a class. Having said this, the preferred way to make it work is to refactor the class so that parameters can identified via class inheritance. This is possible for DDPPlugin, PyTorchProfiler, loggers, etc, and I have thought about looking into how to fix them but haven't had the time for it

The title of this issue makes it seem like if there wasn't support at all for `**kwargs`. Also the yaml snippet does not show `class_path` and `init_args` which is how jsonargparse works, so it is unclear what the proposal is. @quancs please fix.

What I said might be justified to add is only for a very limited scope. It is **not** that all parameters that for a particular class that should go to its `**kwargs` be in this special group in the yaml that skips type checking. It would be only for parameters not determined via class inheritance. It is misleading to use the name of the `kwargs` variable because as you see it would not be like the other parameters.

An example that shows what currently works and what not is the following:

```
class ParentClass:
    def __init__(self, parent_opt1: int = 1):
        self.parent_opt1 = parent_opt1

class ChildClass(ParentClass):
    def __init__(self, child_opt1: int = 2, **kwargs):
        self.child_opt1 = child_opt1
        self.child_op2 = kwargs.pop('child_op2')
        super().__init__(**kwargs)
```

The parameters `parent_opt1` and `child_opt1` are supported as decided by design how this should work. The parameter `child_op2` would not be accepted because it wasn't found via class inheritance. The recommended way to fix this is to change the code so that `child_op2` is given by its own parameter, not as part of `**kwargs`. The same can be said about classes in pytorch-lightning. Certainly there are cases in which it is more difficult to change the code, which is why a new feature could make sense. With this new feature for the class `ChildClass` an accepted yaml would be:

```yaml
class_path: module.ChildClass
init_args:
    parent_op1: 6
    child_opt1: 7
    __unresolved__:
        child_op2: 8
```

In contrast the following yaml would not be accepted:

```yaml
class_path: module.ChildClass
init_args:
    child_opt1: 7
    __unresolved__:
        parent_op1: 6
        child_op2: 8
```

Even though `parent_op1` will go into `**kwargs` the value for this parameter should not be part of the dict proposed in this feature request. Objectives of jsonarparse are to validate the parsed values and promote good practices, and something that allows arbitrarily skipping validation will not be added.

**Comment by quancs** [comment] 2022-01-17 09:14
> The title of this issue makes it seem like if there wasn't support at all for **kwargs. Also the yaml snippet does not show class_path and init_args which is how jsonargparse works, so it is unclear what the proposal is. @quancs please fix.

Updated.

@mauvilsa  For your example, I thought the following config is more natural. And we could also validate `parent_op1`.

```yaml
class_path: module.ChildClass
init_args:
    child_opt1: 7
    kwargs:
        parent_op1: 6
        child_op2: 8
```

**Comment by quancs** [comment] 2022-01-17 09:38
> The *args and **kwargs of the __init__ methods of classes is already supported in a very specific way. They are used to identify more named parameters and their types from parent classes (also see PyTorchLightning/pytorch-lightning#8561 (comment)). This is by design and will continue to be the main way these parameters are supported. 

Changing the way to config, does not mean it's impossible to identify named parameters and their types from parent classes. But, as  jsonargparse already has a way to solve part of the `**` parameters, I'm OK with `__unresolved__` to solve the left.

> Having said this, the preferred way to make it work is to refactor the class so that parameters can identified via class inheritance.

I totally agree with this. But, refactoring everything to meet the requirement of validation is not a easy/convenient way. So, it would great if jsonargparse can support it. ^^

**Comment by cifkao** [comment] 2022-04-11 13:10
Why not add the possibility to tell the parser to skip type checking for certain arguments or classes or (more generally) treat them as different types than annotated?

Knowing how jsonargparse works, I can organize my code accordingly. However, I also often need to use third-party codebases written in different (often not so clean) styles (e.g. without proper type annotations), and it is not feasible to refactor every such piece of code in order to work with jsonargparse. So it would be really useful to be able to modify the parser's behavior simply by calling some methods of the parser, rather than by modifying the code.

**Comment by mauvilsa** [comment] 2022-06-10 16:30
Extended support for `**kwargs` based on [Abstract Syntax Trees (ASTs)](https://docs.python.org/3/library/ast.html) has been added in commit https://github.com/omni-us/jsonargparse/commit/2293160afcf6597c8bb687b848980adc45f1736e. There are cases which it is impossible to handle with ASTs, so I also added the `__unresolved__` feature in commit https://github.com/omni-us/jsonargparse/commit/c20f1a6f2284ad644e2763bc1ef50d5fc6cba73a. You can see the relevant documentation in https://jsonargparse.readthedocs.io/en/latest/#parameter-resolvers.

The `LightningCLI` unit tests pass and I know that most of the classes mentioned in https://github.com/PyTorchLightning/pytorch-lightning/issues/11653 already work. Though in a few days I will be adding unit tests for this in the lightning repo. I will not release this just yet, but feel free to try things out with master. I will close this issue now. Please open new issues for bugs found, improvements, suggestions to change, etc.

**Closed by mauvilsa** 2022-06-10 16:30 UTC
Labels: enhancement

**Comment by mauvilsa** [comment] 2022-06-14 16:08
It was just to avoid name collisions with the parameters. I wasn't happy with it either, but hadn't come up with something better. But now that you mention it, to avoid name collisions it can be placed at the same level as `class_path` and `init_args`, and call it something like `unresolved_init_args`.

**Comment by huangyxi** [comment] 2024-06-05 02:45
A note for followers concerning this feature since https://github.com/omni-us/jsonargparse/commit/10da2c0523d6f04d063ccec392869bcfab7e1212:

> If MyClass.__init__ has **kwargs with some unresolved parameters, the following could be a valid config file:
>
> ```yaml
> class_path: MyClass
> init_args:
>   foo: 1
> dict_kwargs:
>   bar: 2
> ```
> The value for bar will not be validated, but the class will be instantiated as MyClass(foo=1, bar=2).

https://jsonargparse.readthedocs.io/en/stable/#unresolved-parameters
