### ISSUE TITLE
`--help` defaults values doesn't updated with default config files

### ISSUE THREAD

**Issue by stasbel** [omni-us/jsonargparse#47] opened 2021-03-18 18:31 UTC
Thanks for the full --help command.
Couple of small problems I have spotted so far:
* Arguments order is sorted alphabetically (not with respect to time added). Probably related to #46.
* Output contains python objects info, like `... object at 0x7f3670c6dc50`.
* Default values aren't update with having default config files.

**Comment by mauvilsa** [comment] 2021-03-19 07:15
>     * Arguments order is sorted alphabetically (not with respect to time added). Probably related to #46.
In the help I do normally see them in the correct order. It depends on time added and argument groups. Each ActionParser becomes a group so all its arguments should appear together in time added order plus its argument groups. If you can confirm that the order is incorrect, please create an issue with code to reproduce it.

>     * Output contains python objects info, like `... object at 0x7f3670c6dc50`.
I guess this is because of the ActionParser not being given a title. If you give a title it will look okay. Later I will fix it so that if it is not given a title then nothing is shown.

>     * Default values aren't update with having default config files.
From what I see this does work correctly. Note that if no file matches any of the patterns in `default_config_files` then there is no error or warning. Also note that the home prefix `~/` is not yet supported. The test I did is the following. First create a file `config.yaml` with content `op: from yaml`. Then in the same directory run:

```python
>>> from jsonargparse import ArgumentParser
>>> p=ArgumentParser()
>>> p=ArgumentParser(default_config_files=['config.yaml'])
>>> p.add_argument('--op', default='from default')
>>> p.parse_args([])
Namespace(__default_config__=Path(config.yaml, cwd=/Users/mvillegas), op='from yaml')
```

Observe that the Namespace includes a `__default_config__` entry which is a way to know which default config file was loaded.

**Comment by mauvilsa** [comment] 2021-03-19 10:12
> > ```
> > * Output contains python objects info, like `... object at 0x7f3670c6dc50`.
> > ```
> 
> I guess this is because of the ActionParser not being given a title. If you give a title it will look okay. Later I will fix it so that if it is not given a title then nothing is shown.

This is now fixed in the current version in master.

**Comment by stasbel** [comment] 2021-03-20 19:36
> Default values aren't update with having default config files.
Sorry, what I really meant is: "Default values **for --help message** aren't update with having default config files."

**Comment by mauvilsa** [comment] 2021-03-21 07:21
> > Default values aren't update with having default config files.
> 
> Sorry, what I really meant is: "Default values **for --help message** aren't update with having default config files."

My bad. It was clear from the issue title. This can be done.

**Comment by mauvilsa** [comment] 2021-03-22 08:59
In the new release v3.8.0 in the help the titles are no longer object references and the default values are updated from a default config file if present.

**Closed by mauvilsa** 2021-03-22 08:59 UTC
Labels: enhancement
