### ISSUE TITLE
Multilevel subcommand issue

### ISSUE THREAD

**Issue by vadyalex** [omni-us/jsonargparse#158] opened 2022-09-02 14:46 UTC
Thank you creating and maintaining this awesome library!

## 🐛 Bug report

I believe I discovered bug using multiple levels of subcommands after upgrading from `3.1.0` to latest at the time of report `4.13.2`.

### To reproduce

```python
    from jsonargparse import ArgumentParser

    lvl1_parser = ArgumentParser()

    root_parser = ArgumentParser()
    root_subcommands = root_parser.add_subcommands()
    root_subcommands.add_subcommand('lvl1', lvl1_parser)

    lvl2_parser = ArgumentParser()
    # lvl2_parser.add_argument('--unused')

    lvl1_subcommands = lvl1_parser.add_subcommands()
    lvl1_subcommands.add_subcommand('lvl2', lvl2_parser)

    root_parser.parse_args([
        'lvl1', 'lvl2'
    ])
```

Resulting in exception:

```
error: 'Key "lvl2" not found in namespace.'
```

I found workaround by adding "dummy" option to `ArgumentParser` for deepest subcommand, from example above:

```python
    from jsonargparse import ArgumentParser

    lvl1_parser = ArgumentParser()

    root_parser = ArgumentParser()
    root_subcommands = root_parser.add_subcommands()
    root_subcommands.add_subcommand('lvl1', lvl1_parser)

    lvl2_parser = ArgumentParser()
    lvl2_parser.add_argument('--unused') # <-- "dummy" option

    lvl1_subcommands = lvl1_parser.add_subcommands()
    lvl1_subcommands.add_subcommand('lvl2', lvl2_parser)

    assert root_parser.parse_args([
        'lvl1', 'lvl2'
    ]).as_dict() == {'lvl1': {'lvl2': {'unused': None}, 'subcommand': 'lvl2'}, 'subcommand': 'lvl1'}

```

### Environment

- jsonargparse version (e.g., 4.8.0): 4.13.2
- Python version (e.g., 3.9): 3.9
- How jsonargparse was installed (e.g. `pip install jsonargparse[all]`): pip install 'jsonargparse[jsonschema]==4.13.2'
- OS: macOS Monterey 12.5.1

**Comment by mauvilsa** [comment] 2022-09-02 16:34
Thank you for reporting! I had never thought about having a subcommand without any options, but certainly that is a use case. The problem is also observed with a single level subcommand. I just pushed the fix in commit https://github.com/omni-us/jsonargparse/commit/8be44b3709ee1037eb0b5022a6586bf025f259ca. Note that with the fix the result of the example will be:

```python
>>> root_parser.parse_args(['lvl1', 'lvl2']).as_dict()
{'subcommand': 'lvl1', 'lvl1': {'subcommand': 'lvl2'}}
```

**Comment by vadyalex** [comment] 2022-09-02 21:53
Amazing! Thank you! ❤️

When do you think next release will happen?

**Comment by mauvilsa** [comment] 2022-09-06 05:29
This is part of v4.13.3 just released.

**Closed by mauvilsa** 2022-09-06 05:29 UTC
Labels: bug
