### ISSUE TITLE
No action for key "ckpt_path" -> ckpt_path not available for linking

### ISSUE THREAD

**Issue by Toekan** [omni-us/jsonargparse#411] opened 2023-10-24 11:32 UTC
## 🐛 Bug report

Hi,

Thanks for all the hard work on making it possible to configure Lightning experiments through a simple config! Edit: Not sure if this is a bug or something that isn't well documented on the LightningCLI side, but can't seem to find how to change the label now :) 

I want to link my ckpt_path to a callback using link_arguments together wit h LightningCLI (in my case because the callback is used to save out a set of predictions and the ckpt_path is used for naming the prediction set filename, but I would have thought needing your ckpt_path in other places in the config.yaml isn't that uncommon?). This is how I implemented the linking.

```
class MyLightningCLI(LightningCLI):
        def add_arguments_to_parser(self, parser):
            parser.link_arguments("ckpt_path", "trainer.callbacks.init_args.ckpt_path")

cli = MyLightningCLI(
        MyLitModule,
        MyLitDataModule,
        run=True,
    )
```

when running `python predict_my_model.py predict --config my_config.yaml` I unfortunately get the following error:

```
ValueError: No action for key "ckpt_path".
```

Going through the code, it seems like `ckpt_path` does not have an action attached it, [find_parent_or_child_actions](https://github.com/omni-us/jsonargparse/blob/main/jsonargparse/_link_arguments.py#L28) does not find one.

### To reproduce

Can try to construct a dummy example if more is needed than what was given in above section.

### Expected behavior

Being able to access `ckpt_path` when using link arguments.

### Environment

- jsonargparse version: v4.26.1
- Python version: 3.10
- How jsonargparse was installed: `pip install jsonargparse` 
- OS: Linux

**Comment by mauvilsa** [comment] 2023-10-24 20:03
The problem is not in jsonargparse. The error happens because `ckpt_path` is added in line [cli.py#L497](https://github.com/Lightning-AI/lightning/blob/1210deb5a0ff720b0ad66e38149cd28471d760ca/src/lightning/pytorch/cli.py#L497), which is after `add_arguments_to_parser` gets called (line [cli.py#L494](https://github.com/Lightning-AI/lightning/blob/1210deb5a0ff720b0ad66e38149cd28471d760ca/src/lightning/pytorch/cli.py#L494)). That is, when the `link_arguments` is run, `ckpt_path` does not yet exist in the parser.

How can this be fixed? You could override [_prepare_subcommand_parser](https://github.com/Lightning-AI/lightning/blob/1210deb5a0ff720b0ad66e38149cd28471d760ca/src/lightning/pytorch/cli.py#L492), having the same code, but moving `_add_arguments` to be after `add_method_arguments`. Though, note that this method starts with underscore `_`, so not guaranteed to be stable.

There could be other more proper solutions. But maybe this is not the correct place to discuss it. Please create an issue in lightning.

**Comment by Toekan** [comment] 2023-10-28 08:47
Hey @mauvilsa , thank you for the quick and in-depth answer! Sorry for raising it in the wrong place, I'll see if they can change it in lightning :).

**Comment by mauvilsa** [comment] 2023-10-31 06:39
Closing this since the issue in lightning is now open https://github.com/Lightning-AI/lightning/issues/18885

**Closed by mauvilsa** 2023-10-31 06:39 UTC
Labels: question
