### ISSUE TITLE
Support multi-inheritance classes

### ISSUE THREAD

**Issue by florianblume** [omni-us/jsonargparse#143] opened 2022-07-01 20:21 UTC
## 🚀 Feature request

As far as I can tell, currently there's not support for multi-inheritance classes (but of course let me know if I'm wrong or implementing something wrong). The following example throws an error:

```python
from jsonargparse import ArgumentParser
import yaml

class ModelBaseClass():
    def __init__(self, batch_size: int=0):
        self.batch_size = batch_size

class ImageModel(ModelBaseClass):
    def __init__(self, image_size: int=0, **kwargs):
        super().__init__(**kwargs)
        self.image_size = image_size

class ClassModel(ModelBaseClass):
    def __init__(self, num_classes: int=0):
        self.num_classes = num_classes

class ImageClassModel(ImageModel, ClassModel):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

parser = ArgumentParser(
    prog='app',
    description='Description for my app.'
)

parser.add_subclass_arguments(ModelBaseClass, 'model')

model = yaml.safe_dump({
    'class_path': '__main__.ImageClassModel',
    'init_args': {
        'image_size': 5,
        'num_classes': 10
    }
})

print(parser.parse_args([f'--model={model}']))
```

It used to work in the [fork I made off of version 4.8](https://github.com/florianblume/jsonargparse) but somehow stopped to work now.

### Motivation

I guess the example makes it pretty obvious why this is a neat feature, it just makes sense to separate the classes like this (maybe you have a classifier that is not classifying images) but also compose them again.

### Pitch

It would be cool if it would work again like in version 4.8 :) I'd also happy to help out if it's a simpler fix but it might be faster/nicer coded if you do it yourself ;)

### Alternatives

Not really any that I can think of.

**Comment by mauvilsa** [comment] 2022-07-04 06:19
This worked before, making it a regression. So changed the issue from enhancement to bug.

**Comment by mauvilsa** [comment] 2022-07-04 06:38
This is fixed in commit https://github.com/omni-us/jsonargparse/commit/57fe54861c4053df746e496bafbad737cdbc62cc. Note that there is a mistake in the code snippet you included above. Creating an instance of `ImageClassModel` will not call `ModelBaseClass.__init__`, which means that `batch_size` will not be set. This can be observed by running `list(ImageClassModel().__dict__.keys())` which gives `['num_classes', 'image_size']`. The problem is that `ClassModel` is missing `super().__init__(**kwargs)`. Without fixing that code, jsonargparse will work the same way, not accepting the parameter `batch_size`.

**Closed by mauvilsa** 2022-07-04 06:38 UTC
Labels: bug

**Comment by florianblume** [comment] 2022-07-04 11:31
Nice, works perfectly. Thanks about mentioning the bug in the example script, it's not actual code but I wrote it from scratch, that's probably why this error is in there.

I'd love to directly implement a fix next time but every time I look at your changes I get that I don't understand the project well enough for that, yet... So thanks a lot for your work!
