### ISSUE TITLE
Defining class_path before init_args does not work, but switching the order does work.

### ISSUE THREAD

**Issue by basveeling** [omni-us/jsonargparse#161] opened 2022-09-23 13:14 UTC
## 🐛 Bug report

Using LightningCLI, when setting the `model` property in a yaml file, the order of class_path and init_args matters. class_path before init_args causes a ParsingError.

### To reproduce

Setup a LightingCLI with a base class BaseModelClass(LightningModule)
`train.py` would be something along the lines of
```
LightningCLI(model_class=BaseModelClass, ...)
```

Config file `a.yaml`:
```
model:
   class_path: SubclassedModelClass
   init_args:
     a: b
```

Config file `b.yaml`
```
model:
   init_args:
     a: b
   class_path: SubclassedModelClass
```
Run it as follows
`python train.py fit -c a.yaml`

```
jsonargparse.util.ParserError: Configuration check failed :: Parser key "model": Type <class 'BaseModelClass'> expects: a class path (str); or a dict with a class_path entry; or a dict with init_args (if class path given previously). Got "Namespace(init_args=Namespace(a="b"))".
```
(Notice the missing **class_path**)

Then run with the alternative order
`python train.py fit -c b.yaml`
Which runs successfully.

### Expected behavior

Both orders should work

### Environment

- jsonargparse version 4.14.0
- pytorch_lightning 1.7.4
- python 3.8.14
- `pip install jsonargparse[signatures]`
- Ubuntu

**Comment by mauvilsa** [comment] 2022-09-24 13:49
Thank you for reporting. I tried a few things, but unfortunately I am unable to reproduce it. From the description I wrote:

```python
from pytorch_lightning import LightningModule
from pytorch_lightning.cli import LightningCLI

class BaseModelClass(LightningModule):
    def __init__(self, a: str = '-'):
        pass

class SubclassedModelClass(BaseModelClass):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

LightningCLI(
    model_class=BaseModelClass,
    subclass_mode_model=True,
)
```

If I run this with the two config files you posted, both `./cli.py fit -c a.yaml --print_config` and `./cli.py fit -c b.yaml --print_config` work correctly (`--print_config` added just to stop after parsing).

If by mistake `subclass_mode_model=True` is missing, it doesn't fail when it should. This is a bug which I will fix, but it is not the problem you reported. Please check again and complete the code in the description so that it can be reproduced.

**Comment by basveeling** [comment] 2022-09-24 14:37
Thank you for looking into this and setting up a proper reproduction code
snippet. Apologies for not doing this myself, I was short on time. I’ll try
and run your example in our environment and see if we get the same issue.

**Comment by mauvilsa** [comment] 2022-10-07 10:17
Any update on this?

**Comment by mauvilsa** [comment] 2022-12-27 13:25
I assume you were not able to reproduce the issue. Closing.

**Closed by mauvilsa** 2022-12-27 13:25 UTC
Labels: bug
