### ISSUE TITLE
Fields of optional dataclasses are not displayed in the generated help

### ISSUE THREAD

**Issue by maticus** [omni-us/jsonargparse#509] opened 2024-05-23 07:23 UTC
## 🐛 Bug report

Prompted by the super-quick fix of #507 (thanks!) I'm doing some more testing of jsonargparse with nested optional dataclasses, and found out:

Fields of optional dataclasses are not displayed in the generated help

### To reproduce

Following script
```
import jsonargparse
from typing import Optional
from dataclasses import dataclass

@dataclass
class B:
    c: int = 3

@dataclass
class A:
    b: B
    ob: Optional[B]

def fun(a: A):
    print(a)

jsonargparse.CLI(fun)
```

when ran: 
`python python-jsonargparse-optional-dataclass.py -h`

displays:

```
...
  -h, --help            Show this help message and exit.
  --config CONFIG       Path to a configuration file.
  --print_config[=flags]
                        Print the configuration after applying all other arguments and exit. The optional flags customizes the output and
                        are one or more keywords separated by comma. The supported flags are: comments, skip_default, skip_null.

A(b: __main__.B, ob: Optional[__main__.B]):
  --a CONFIG            Path to a configuration file.
  --a.ob OB             (type: Optional[B], default: null)

B(c: int = 3):
  --a.b CONFIG          Path to a configuration file.
  --a.b.c C             (type: int, default: 3)
```

Note, `--a.ob.c` is missing, but I can configure using this option:
```
$ python python-jsonargparse-optional-dataclass.py  --a.b.c 77 --a.ob.c 78
A(b=B(c=77), ob=B(c=78))
```

### Expected behavior

The `--a.ob.c` option should also be displayed in the help.

### Environment

- jsonargparse version: today's master :-) (git-describe: v4.28.0-10-gf44ba32)
- Python version: 3.10
- How jsonargparse was installed: `pip install -e ".[dev,all]"` from checked-out repo.
- OS: Ubuntu Jammy

**Comment by mauvilsa** [comment] 2024-05-23 19:26
Thank you for reporting! This is actually a feature request duplicate of #368. The proposal is to do as described in https://github.com/omni-us/jsonargparse/issues/368#issuecomment-1705438863, though this hasn't yet been implemented. I will close this issue in favor of the previous one.

**Closed** 2024-05-23 19:27 UTC
Labels: duplicate, enhancement
