### ISSUE TITLE
`CLI` fails to instantiate `pydantic` classes

### ISSUE THREAD

**Issue by rusmux** [omni-us/jsonargparse#503] opened 2024-05-19 22:02 UTC
## 🐛 Bug report

`CLI` fails to instantiate `pydantic` classes.

### To reproduce

In `main.py`:

```Python
import jsonargparse
import pydantic


class MyClass1(pydantic.BaseModel):
    a: int


class MyClass2(pydantic.BaseModel):
    b: int


def func(instance: pydantic.BaseModel) -> None:
    print(instance)


if __name__ == "__main__":
    jsonargparse.CLI(func)
```

In `config.yaml`:

```Yaml
instance:
  class_path: __main__.MyClass1
  init_args:
    a: 1
```

In terminal:

```bash
python -m main --config config.yaml
```

### Expected behavior

Program should exit with zero code.

It does work If I change `pydantic` classes to normal classes.

### Environment

- jsonargparse version (e.g., 4.8.0): 4.28.0
- pydantic version: 2.7.1
- Python version (e.g., 3.9): 3.9.19
- How jsonargparse was installed (e.g. `pip install jsonargparse[all]`): `pip install jsonargparse[all]`
- OS (e.g., Linux): macOS

**Comment by mauvilsa** [comment] 2024-05-20 05:58
Thank you for reporting!

This is not a bug. Pydantic classes behave like subclasses, which means, they don't behave like subclasses and don't accept `class_path` to select a derived class. This could be considered a duplicate of #287, since the fix will be the same: a new feature that allows developers to select which classes and which not behave as subclasses.

Running the reproduction code, I do see a bug. The parsing is not failing with an error saying `class_path` and `init_args` are unexpected. Which is why the failure is on instantiation making it misleading.

**Comment by mauvilsa** [comment] 2024-06-09 08:54
Closing this in favor of #287.

**Closed** 2024-06-09 08:55 UTC
Labels: duplicate, enhancement
